version: "3.7"
services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    command:
      --character-set-server=utf8
      --collation-server=utf8_general_ci
      --performance-schema=off
  app:
    depends_on:
      - mysqldb
    build:
      context: .
    restart: on-failure
    env_file: ./.env
    ports:
      - '8080:8080'
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/$MYSQLDB_DATABASE?characterEncoding=UTF-8",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_PASSWORD",
        "storage.s3.bucket-name" : "$S3_BUCKET_NAME",
        "storage.s3.access-key" : "$S3_ACCESS_KEY",
        "storage.s3.secret-key" : "$S3_SECRET_KEY",
        "deploy.security.require-https" : "$DEPLOY_SECURITY_REQUIRE_HTTPS"
      }'
      JDK_JAVA_OPTIONS: '-Xmx128M'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db:
